package com.shopee.ecommer.constants;

public enum MessageErrors {
    //UnAuthorized
    USER_UNAUTHORIZED,
    //ACCOUNT
    ACCOUNT_USERNAME_INVALID,
    ACCOUNT_USERNAME_IS_EXISTS,
    ACCOUNT_LIST_FIELD_INVALID,
    ACCOUNT_PASSWORD_INVALID,

    //CATEGORY
    CATEGORY_NAME_INVALID,
    CATEGORY_LIST_FIELD_INVALID,
    CATEGORY_IMAGE_INVALID,

    //PRODUCT
    PRODUCT_NAME_INVALID,
    PRODUCT_LIST_FIELD_INVALID,
    PRODUCT_IMAGE_INVALID,
    PRODUCT_QUANTITY_INVALID,
    PRODUCT_PRICE_INVALID,
    PRODUCT_DISCOUNT_INVALID,
    PRODUCT_ID_CATEGORY_INVALID,
    PRODUCT_CATEGORY_INVALID,
    PRODUCT_CATEGORY_NOT_EXISTS

}
