spring:
  application:
    name: admin
  profiles:
    active: dev
  server:
    port: 8080
    #Note: false when in localhost, and true for another env
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  config:
    import: "optional:configserver:http://localhost:8071/"