custom:
  rabbit-mq:
    queue: email-registration
  email:
    url: http://localhost:9000
  security:
    clientId: admin
    clientSecret: password
    oauth2Url: http://localhost:8070
spring:
  # Vault
  #  cloud:
  #    vault:
  #      scheme: http
  #      host: 127.0.0.1
  #      port: 8200
  #      token: 18456350-7b89-11ed-85e9-a5830358e351
  #  config:
  #    import: vault://
  # RabbitMQ
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
  # PostgreSQL
  datasource:
    hikari:
      connectionTimeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=qa_shopee
    username: postgres
    password: postgres
  # Flyway
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: qa_shopee
    password: postgres
    user: postgres
    enabled: true
    validate-migration-naming: true
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070