spring:
  application:
    name: admin
  profiles:
    active: dev
  server:
    port: 8080
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    gateway:
      httpClient:
        connect-timeout: 10000
        response-timeout: 20s
  config:
    import: "optional:configserver:http://localhost:8071/"