spring:
  application:
    name: admin
  profiles:
    active: dev
  server:
    port: 8080
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    gateway:
      httpClient:
        connect-timeout: 10000
        response-timeout: 20s
  config:
    import: "optional:configserver:http://localhost:8071/"


#Spring doc
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

#MyBatis
mybatis:
  mapper-locations: classpath:batis/*.xml
  type-aliases-package: com.shopee.shopeebeadmindemo.mybatis
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Config Eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
info:
  app:
    name: "admins"
    description: "Shopee be admin demo"
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 10000
      limitRefreshPeriod: 5000
      limitForPeriod: 1