spring:
  profiles:
    active: dev
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  application:
    name: shopee_local
#  cloud:
#    vault:
#      kv:
#        enabled: true
#      authentication: TOKEN

mybatis:
  mapper-locations: classpath:batis/*.xml
  type-aliases-package: com.shopee.shopeebeadmindemo.mybatis



